az_location                         = "australiacentral"
az_storage_account_name             = "mysa124" # this value has to be globally unique or else the creation will fail
az_storage_account_type             = "Standard_LRS"
az_storage_account_replication_type = "LRS"
az_subscription_id                  = "16982123-2d3c-44ce-ab2d-0c419f4ce699"
az_container_access_type            = "blob"
az_virtualnetwork_adress_space      = ["10.0.0.0/16"]
az_resource_group_name              = "learn-08d925fa-b41a-41bb-a07d-e13fd9bc57fd" # to be manually given from azure
az_virtualnetwork_name              = "myVnet"
